HexBot: 
  Roles: 
    Admin: 
      Title: "ADMIN"
      Description: "Admin"
    Premium: 
      Title: "PREMIUM"
      Description: "Premium"
    Basic: 
      Title: "BASIC"
      Description: "Basic"
  Commands: 
    Whois: 
      Status: 
        Invalid: "🔴 Failed"
        Success: "🟢 Successed"
    Resolver: 
      Status: 
        Offline: "🔴 Offline"
        Online: "🟢 Online"
    Protocols: 
      # {version} => 1.12.x
      # {protocols} => 340
      Format: "`{version} ({protocols})`"
      Separator: ","
    Methods:
      NoneMethods: "```❌ This type doesn't have any methods!```"
      NoRole: "```❌ You don't have required role to see this methods!```"
      Format: "`{methods_id}`"
      Separator: ","
          
  